# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HttpsDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HttpsDemo
  pod 'AFNetworking'

  target 'HttpsDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HttpsDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
