# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ASDisplayDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ASDisplayDemo
 pod 'Texture'
  target 'ASDisplayDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ASDisplayDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
