# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BaseNavigationDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BaseNavigationDemo
  pod "RTRootNavigationController"
  pod 'FDFullscreenPopGesture', '~> 1.1'

  target 'BaseNavigationDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BaseNavigationDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
